@startuml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Component.puml

LAYOUT_WITH_LEGEND()

System_Ext(cinepolis, "Cinepolis", "Provider's web page. Allows to the system scrape information about movies, locations and schedules")
System_Ext(cinemex, "Cinemex", "Provider's web page. Allows to the system scrape information about movies, locations and schedules")
Container(db, "Database", "No Relational Database Schema(MongoDb)", "Stores movies, theaters, brand information as date, time, name, title, logo and etc...")
Container_Boundary(api, "CLI Application") {
    Component(scrapper, "Template", "Layer", "Define template pattern. Common actions to be perform to extract all needed information")
    Component(implCinepolis, "Implementation", "Cinepolis", "Scrape HTML with especific rules and particular CSS selectors")
    Component(implCinemex, "Implementation", "Cinemex", "Scrape HTML with especific rules and particular CSS selectors")
    Component(connector, "Uses Cases", "Layer", "Received unified information and persist it into the database")

    Rel(scrapper, implCinepolis, "Uses")
    Rel(scrapper, implCinemex, "Uses")
    Rel(implCinepolis, connector, "Uses")
    Rel(implCinemex, connector, "Uses")
}
Rel(implCinepolis, cinepolis, "Uses")
Rel(implCinemex, cinemex, "Uses")
Rel(connector, db, "Uses")
@enduml
